In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# scikit-learn

Բացի ``numpy``-ից և ``pandas``-ից այլ գրադարանների օգտագործումն **արգելված է**։

**Error handling**

>1․ Եթե որպես ֆունկցիայի պարամետր ստանում եք numpy զանգված (վեկտոր կամ մատրից), և այն չի համապատասխանում խնդրում նշված չափին (dimensions) կամ չափերի անհամաձայնություններ կան, ապա վերադարցրեք(return) **"DimensionError"** տեքստը

# Homework Exercises

Problem1. Տրված են՝ 

data $\rightarrow$ numpy մատրից $150 \times 4$ չափի

feature_names $\rightarrow$ string-երի list 4 էլեմենտներով

target $\rightarrow$ numpy վեկտոր $150$ չափի

target_names $\rightarrow$ string-երի list 3 էլեմենտներով

փոփոխականները (որոնք ստեղծված են վերևում)։ Պահանջվում է ստեղծել pandas DataFrame որը կունենա 5 սյուն և 150 տող։ Առաջին 4 սյուներում գրված կլինի 'data' փոփոխականի պարունակությունը։ Իսկ հինգերորդ սյան մեջ կլինի 'target'-ը, բայց ամեն թվի փոխարեն գրված 'target_names'-ի համապատասխան ինդեքսով տարրը։ Առաջին 4 սյուների անունները կլինեն  'feature_names'-ի էլեմենտները (տրված հերթականությամբ), իսկ հինգերորդի անունը կլինի "target name": 

Վերջնական DataFrame-ի առաջին 5 տողերը կունենան հետևյալ տեսքը՝
```
	sepal length (cm)	sepal width (cm)	petal length (cm)	petal width (cm)	target name
0	     5.1             	3.5	                1.4	           0.2	          setosa
1	     4.9            	 3.0                	1.4           	0.2	          setosa
2	     4.7             	3.2                	1.3           	0.2	          setosa
3	     4.6	             3.1                	1.5           	0.2	          setosa
4	     5.0             	3.6                	1.4           	0.2	          setosa
```

**Ստացված DataFrame֊ը օգտագործվելու է հաջորդ խնդիրներում**։

In [ ]:
# Run this cell
# Do not modify this cell
from sklearn.datasets import load_iris
iris = load_iris()

data = iris['data']
feature_names = iris['feature_names']
target = iris['target']
target_names = iris['target_names']

print('First 5 rows:', data[:5], sep='\n', end='\n\n')
print('Feature names:', feature_names, sep='\n', end='\n\n')
print('Target indices:', target, sep='\n', end='\n\n')
print('Target names:', target_names, sep='\n')

In [ ]:
def get_data_frame(data, feature_names, target, target_names):
  
  tmp = pd.DataFrame(data, columns = feature_names)
  
  tmp["target name"] = target_names[target]
  
  return tmp

In [ ]:
# Do not modify this cell
df = get_data_frame(data, feature_names, target, target_names)

assert isinstance(df, pd.DataFrame)
assert df.shape == (150, 5)
assert np.all(df.loc[[0, 75, 120], 'target name'].values == target_names)

Նախորդ խնդրում ստացված ``df`` աղյուսակի մեջ գրված է ծաղիկների թերթիկների (պսակաթերթի և բաժակաթերթի) երկարությունն ու լայնությունը և համապատասխան ծաղիկի համարը։ {'setosa', 'versicolor', 'virginica'} տեսակները կոդավորված են {0,1,2} թվերով։

![picture](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRaU43Ra3xTYTpU2XLBw5yl20Qty3OCJzjDBw&usqp=CAU)

Problem2. Գտեք յուրաքանչուր ծաղկատեսակի թերթիկի (պսակաթերթ և բաժակաթերթ)

1. միջին երկարությունը
2. միջին լայնությունը
3. նվազագույն երկարությունը
4. նվազագույն լայնությունը
5. առավելագույն երկարությունը
6. առավելագույն լայնությունը

Այս ամենը լցրեք pandas DataFrame-ի մեջ որը ունի հետևյալ սյուները` 
```python
["mean sepal length (cm)", "mean petal length (cm)", "mean sepal width (cm)", "mean petal width (cm)", "min sepal length (cm)", "min petal length (cm)", "min sepal width (cm)", "min petal width (cm)", "max sepal length (cm)", "max petal length (cm)", "max sepal width (cm)", "max petal width (cm)"]
```
և "target name" ինդեքսը։ Խորհուրդ է տրվում օգտագործել ``pd.group_by`` ֆունկցիան։

In [ ]:
def get_stats(df):
  setosa = df[df['target name'] == 'setosa'][feature_names].mean().values
  virginica = df[df['target name'] == 'virginica'][feature_names].mean().values
  versicolor = df[df['target name'] == 'versicolor'][feature_names].mean().values

  setosa_min = df[df['target name'] == 'setosa'][feature_names].min().values
  virginica_min = df[df['target name'] == 'virginica'][feature_names].min().values
  versicolor_min = df[df['target name'] == 'versicolor'][feature_names].min().values

  setosa_max = df[df['target name'] == 'setosa'][feature_names].max().values
  virginica_max = df[df['target name'] == 'virginica'][feature_names].max().values
  versicolor_max = df[df['target name'] == 'versicolor'][feature_names].max().values

  rows1, row2, rows3 = np.hstack([setosa, setosa_min, setosa_max]), np.hstack([virginica, virginica_min, virginica_max]), np.hstack([versicolor, versicolor_min, versicolor_max])

  columns = np.array([[a + ' sepal length (cm)', a + ' sepal width (cm)', a + ' petal length (cm)', a + ' petal width (cm)'] for a in ['mean', 'min', 'max']]).flatten()

  a = pd.DataFrame(np.vstack([rows1, rows3, row2]), columns = columns)
  a.index = np.array(['setosa', 'versicolor', 'virginica'])
  a.index.name = 'target name'
  return a[["mean sepal length (cm)", "mean petal length (cm)", "mean sepal width (cm)", "mean petal width (cm)", "min sepal length (cm)", "min petal length (cm)", "min sepal width (cm)", "min petal width (cm)", "max sepal length (cm)", "max petal length (cm)", "max sepal width (cm)", "max petal width (cm)"]]

In [ ]:
# Do not modify this cell
df_stats = get_stats(df)
assert df_stats.shape == (3, 12)
assert all(df_stats.index.to_list() == target_names)
assert np.allclose(df_stats.loc[:, "mean sepal length (cm)"].values,
            np.array([5.006, 5.936, 6.588]))
assert np.allclose(df_stats.loc[:, "min petal width (cm)"].values,
            np.array([0.1, 1.0, 1.4]))
assert np.allclose(df_stats.loc[:, "max petal length (cm)"].values,
            np.array([1.9, 5.1, 6.9]))

In [ ]:
df_stats

Problem3. ``df`` աղյուսակից ջնջեք այն տողերը, որոնց 'sepal width'-ը փոքր է իր տեսակի միջինից (օգտվելով նախորդ խնդրի հաշվարկներից ``df_stats``)։ Փոփոխությունը կատարեք ``df``-ի վրա և ֆունկցիայով ոչինչ մի վերադարձրեք։

In [ ]:
def remove_small_flowers(df, df_stats):
  #Your code here
  meanS = df_stats["mean sepal width (cm)"][0]
  meanVer = df_stats["mean sepal width (cm)"][1]
  meanVirg = df_stats["mean sepal width (cm)"][2]

  result_set = np.vstack([(df["sepal width (cm)"][:50] < meanS).values, (df["sepal width (cm)"][50:100] < meanVer).values, (df["sepal width (cm)"][100:150] < meanVirg).values]).flatten()
  ind = df[result_set].index
  df.drop(index=ind, inplace = True)

In [ ]:
# Do not modify this cell
assert remove_small_flowers(df, df_stats) is None
assert df.shape == (80, 5)
assert (df[['petal length (cm)']].min() == 1.0)[0]
assert (df[['petal length (cm)']].max() == 6.7)[0]

Ստորև վանդակն աշխատացնելով ներմուծիր Բոստոն $506\times13$  չափանի տվյալների բազմությունը, որն իր մեջ պարունակում է Բոստոնի 506 թաղամասերի վերաբերյալ տվյալներ՝ 13 բնութագրիչներով։ Այդ բնութագրիչներն են՝

("ԱՆՈՒՆ բացատրություն" ֆորմատով)
1. CRIM per capita crime rate by town
2. ZN proportion of residential land zoned for lots over 25,000 sq.ft.
3. INDUS proportion of non-retail business acres per town
4. CHAS Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
5. NOX nitric oxides concentration (parts per 10 million)
6. RM average number of rooms per dwelling
7. AGE proportion of owner-occupied units built prior to 1940
8. DIS weighted distances to five Boston employment centres
9. RAD index of accessibility to radial highways
10. TAX full-value property-tax rate per $10,000
11. PTRATIO pupil-teacher ratio by town
12. B 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
13. LSTAT % lower status of the population


Իսկ *y փոփոխականը* 506 երկարությամբ numpy վեկտոր է, որը իրենից ներկայացնում է համապատասխան թաղամասերի տների մեդիան գինը (չափման միավորը՝ $1000)։

Problem4. Ստեղծեք dataframe X, y  փոփոխականների հիման վրա (Problem 1.-ի նման)։ Բնութագրիչ սյուների անունները սահմանեք ըստ վերը նշված ցանկիժ, իսկ վերջին սյան անունը՝  "MEDV"։

In [ ]:
from sklearn.datasets import load_boston
load_boston()

In [ ]:
# Do not modify this cell
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
print(X.shape)

In [ ]:
def get_data_frame(X, y):
  #Your code here
  columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT']
  df = pd.DataFrame(X, columns=columns)
  df['MEDV'] = y
  return df
  #Your code here

In [ ]:
# Do not modify this cell
df = get_data_frame(X,y)

assert isinstance(df, pd.DataFrame)
assert df.shape == (506, 14)
assert df.columns.tolist()[:3] == ['CRIM','ZN','INDUS']
assert df.columns[-1] == 'MEDV'

In [ ]:
# df[df['CHAS'].isna()]
pd.set_option('display.max_rows', None)
df[df['CHAS'] == 1].sort_values(by='MEDV', ascending=False)[:6]

Problem5. Վերադարձնել 3 "ամենաէժան թաղամասերի" տողերը, որտեղ CRIM-ը մեծ է 0.5֊ից։

In [ ]:
def three_less_expensive(df):
  df = df.sort_values('MEDV')
  return df.loc[df['CRIM'] > 0.5][:3]

In [ ]:
# Do not modify this cell
top3 = three_less_expensive(df)
assert top3.MEDV.mean() == 5.2  
assert top3.INDUS.mean() == 18.1 
assert top3.TAX.mean() == 666.0

Problem6. Վերադարձնել 6 "ամենաթանկ թաղամասերի" տողերը, որոնք գտնվում են Չարլզ գետի ափին։

In [ ]:
def three_most_expensive(df):
  df = df.sort_values('MEDV',ascending = False)
  return df.loc[df['CHAS'] == 1.0][:6]

In [ ]:
# Do not modify this cell
top6 = three_most_expensive(df)
assert top6.MEDV.mean() == 50.0
assert top6.TAX.min() == 198.0
assert top6.ZN.max() == 90.0
assert isinstance(top6, pd.DataFrame)

Problem7. Վերադարձնել միջինում 10 ամենաշատ  սենյակներն ունեցող թաղամասերի միջին սենյակների քանակները (``RM``) և տների մեդիան գները։ Արդյունքը պետք է լինի $10 \times 2$ չափանի DataFrame՝ դասավորված ըստ ``RM`` սյան նվազման կարգով։

In [ ]:
def ten_most_rooms(df):
  df = df.sort_values('RM',ascending = False)
  df1 = pd.DataFrame(data = df[:10], columns = ['RM','MEDV',])
  return df1

In [ ]:
# Do not modify this cell
top10 = ten_most_rooms(df)
assert top10.iloc[0].values.tolist() ==  [8.78, 21.9]
assert top10.mean().values.tolist() == [8.4388, 44.83]

Problem8. ``df``-ում ավելացնել նոր տող ըստ տրված 14 երկարությամբ ``x`` վեկտորի։

In [ ]:
def add_row(df, x):
  df.append(pd.Series(x, index=df.columns), ignore_index=True)
  #df.loc[-1] = (x)
  #df.concat([df, x], ignore_index=True)

In [ ]:
# Do not modify this cell
assert len(df) == 506
x = np.array([0.006, 18, 2.31, 0, 0.5, 6.5, 65, 4, 1, 296, 15, 396, 5, 19])
assert add_row(df, x) is None
assert len(df) == 507
assert (df.iloc[-1].values == x).all()

Problem9. ``df``-ից ջնջել առաջին սյունը։

In [ ]:
def remove_first_col(df):
  df.drop(df.columns[[0]], axis=1, inplace=True)

In [ ]:
# Do not modify this cell
assert df.shape[1] == 14
assert remove_first_col(df) is None
assert df.shape[1] == 13
assert df.columns[0] == 'ZN'
assert 'CRIM' not in df.columns

Problem10. Օգտագործելով ``groupby`` ֆունկցիան գտնել գետի մոտ գտնվող և չգտնվող թաղամասերի բնութագրիչների միջինները։

In [ ]:
def group_by_river(df):
  return df.groupby('CHAS').mean()

In [ ]:
# Do not modify this cell
river_df = group_by_river(df)
assert river_df.shape == (2, 12)
assert river_df.index.name == 'CHAS'
#assert river_df.MEDV.values.tolist() == [22.08728813559324, 28.44]

Problem11. ``'Military Expenditure.csv'`` ֆայլի տվյալները կարդացեք DataFrame-ով և վերադարձրեք առաջին 10 տողերը, ինչպես նաև ամբողջ DataFrame-ը։

In [ ]:
def read_return_top10(file_name):
  data = pd.read_csv(file_name)
  df = pd.DataFrame(data)
  dfFirst = df[:10]
  return dfFirst, df

In [ ]:
# Do not modify this cell
top10, df = read_return_top10('Military Expenditure.csv')
assert top10.iloc[8]['Name'] == 'Armenia'
assert top10.shape == (10, 63)

Military Expenditure dataset-ը պատրաստվել է Ստոկհոլմի խաղաղության միջազգային հետազոտությունների ինստիտուտի (SIPRI) կողմից և պարունակում է ավելի քան 200 պետությունների 1960-2018 թվականներին կատարած ռազմական ծախսերը դոլարներով։

Problem12. Ջնջել այն տողերը որոնց 'Type' սյունը "Country" *չէ*։

In [ ]:
def remove_non_countries(df):
  index = df[df['Type']!='Country'].index
  df.drop(index,inplace=True)

In [ ]:
# Do not modify this cell
assert remove_non_countries(df) is None
assert df.Type.nunique() == 1
assert df.shape == (202, 63)

Problem13. Ջնջել 'Code', 'Type', 'Indicator Name' սյուները։

In [ ]:
def remove_some_cols(df):
  df.drop(['Code', 'Type','Indicator Name'], axis=1, inplace=True)

In [ ]:
# Do not modify this cell
assert remove_some_cols(df) is None
assert df.shape == (202, 60)
assert df.columns[1] == '1960'

Problem14. Ստացված dataframe-ը գրել(պահպանել) 'MilitaryExpenditureSmall.csv' ֆայլի վրա **այնպես, ինչպես որ կա**։

In [ ]:
def save_df(df, file_name):
  df.to_csv(file_name,index=False)

In [ ]:
# Do not modify this cell
file_name = 'MilitaryExpenditureSmall.csv'
save_df(df, file_name)
small_df = pd.read_csv(file_name)
assert small_df.iloc[0, 0] == 'Aruba'
assert small_df.shape[1] == 60

Problem15. Վերադարձնել Հայաստանին համապատասխանող տողի այն տվյալները/վանդակները որոնք դատարկ չեն։

In [ ]:
def info_arm(df):
  index = df[df['Name'] !='Armenia'].index
  test = df.drop(index)
  test.dropna(axis=1,inplace= True  )
  return test

In [ ]:
# Do not modify this cell
arm = info_arm(df)
assert arm.shape == (1, 26)
assert arm.iloc[:, 1:].max(axis=1).values[0] == 608854649.9
assert '1994' not in arm.columns

Problem16. Վերադարձնել DataFrame, որտեղ կլինի պետության անունը՝ որպես ինդեքս և յուրաքանչյուր պետության միջին տարեկան ծախսը՝ որպես ``'mean_expense'`` սյուն՝ գրված նվազման կարգով։  Վերջնական աղյուսակում չպետք է լինեն այնպիսի երկրներ, որոնց ծախսերի տվյալները ընդհանրապես առկա չեն կամ 0 են։

In [ ]:
def per_country_mean_expense(df):
  df2 = pd.DataFrame(data = df.mean(axis=1), columns = ['mean_expense'])
  df2.index = df['Name']
  df2.dropna(inplace = True)
  df2 = df2.loc[df2['mean_expense'] != 0]
  df2 = df2.sort_values('mean_expense',ascending= False)
  return df2

In [ ]:
# Do not modify this cell
grouped_df = per_country_mean_expense(df)
assert grouped_df.loc['Armenia'][0] == arm.iloc[:,1:].mean(axis=1).values[0]
assert grouped_df.shape == (164, 1)
assert grouped_df.index[0] == 'United States'
assert grouped_df.index[-1] == 'Haiti'

Problem17. Տրված է ՝ $10 \times 4$ չափնի ```pandas.DataFrame (df)```։ Հարկավոր է գրել ֆունկցիա, որը կստեղծի նոր ```pandas.DataFrame```, որի մեջ կլինեն ```df```-ի տողերն ու սյուները և 2 նոր սյուն ```nearest_row```  և ```dist``` որոնց մեջ գրված կլինեն ամենամոտիկ տողի ```index```-ը և էվկլիդյան հեռավորությունը այդ տողերի միջև։

In [ ]:
def add_columns(df):
  # Your code here

In [ ]:
# Do not modify this cell
np.random.seed(42)
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1),
                  columns=list('pqrs'),
                  index=list('abcdefghij'))
new_df = add_columns(df)
assert isinstance(new_df, pd.DataFrame) 
assert new_df.loc['a']['nearest_row'] == 'g' 
assert new_df.nearest_row.value_counts()[0] == 4
assert id(new_df) != id(df)

Problem18. Տրված է՝ $93 \times 27 $ չափանի ```pandas.DataFrame (df)```։ Հարկավոր է գրել ֆունկցիա, որը կստեղծի նոր ```pandas.DataFrame```, որի մեջ կլինեն ```df```-ի տողերն ու սյուները, բացառությամբ ```Type``` սյան, որի փոխարեն կլինեն մի քանի սյուներ՝ ստացված HW4-ի 4-րդ խնդրի ֆունկցիայի միջոցով։ Սյուների անունները կլինեն ```Type``` սյան արժեքները (Midsize, Small, ...):

In [ ]:
def convert(df):
  df.drop(['Type'], axis=1, inplace=True)
  print(df)

In [ ]:
# Do not modify this cell
df = pd.read_csv(
    'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
new_df = convert(df)
assert convert(df).iloc[0]['Small'] == 1 
assert isinstance(new_df, pd.DataFrame)
assert id(new_df) != id(df)
assert new_df.shape == (93, 32)
assert new_df.columns[-5:].tolist() == ['Large', 'Midsize',
                                        'Small', 'Sporty', 'Van']

Problem19. Նախորդ խնդրում ստացված dataset-ի  ```Min.price``` և ```Max.price``` սյուների բացակայող արժեքները լրացնել համապատասխանաբար այդ սյուների  միջինով և մեդիանով՝ օգտագործելով ``apply()`` մեթոդը:

In [ ]:
def fill_NaN(df):
  # Your code here

In [ ]:
# Do not modify this cell
assert isinstance(new_df, pd.DataFrame)
other_df = fill_NaN(new_df)
assert abs(other_df.iloc[3]['Min.Price'] - 17.118605) < 0.0001
assert abs(other_df.iloc[4]['Max.Price'] - 19.15) < 0.0001